// ============================================================
// Geography map game — pure logic (no React, no network).
//
// Dataset access, continent grouping, neighbour lookup (for the
// 4-card hint), answer normalization + Levenshtein grading, and
// hint/score helpers. Data is bundled (generated by build-geo.ts).
// ============================================================

import { COUNTRIES, type GeoCountry } from '@/content/geo/countries';
import { currentLocale } from '@/i18n';
import type { Locale } from '@/types';

export type { GeoCountry };

// ---- Continents -------------------------------------------

export interface ContinentMeta {
  key: string; // matches GeoCountry.continent
  name: { en: string; no: string };
  emoji: string;
}

// Display order for the picker.
export const CONTINENTS: ContinentMeta[] = [
  { key: 'Europe', name: { en: 'Europe', no: 'Europa' }, emoji: '🏰' },
  { key: 'Africa', name: { en: 'Africa', no: 'Afrika' }, emoji: '🦁' },
  { key: 'Asia', name: { en: 'Asia', no: 'Asia' }, emoji: '🐼' },
  { key: 'North America', name: { en: 'North America', no: 'Nord-Amerika' }, emoji: '🦅' },
  { key: 'South America', name: { en: 'South America', no: 'Sør-Amerika' }, emoji: '🦜' },
  { key: 'Oceania', name: { en: 'Oceania', no: 'Oseania' }, emoji: '🦘' }
];

export function continentMeta(key: string): ContinentMeta | undefined {
  return CONTINENTS.find((c) => c.key === key);
}

export function countriesIn(continent: string): GeoCountry[] {
  return COUNTRIES.filter((c) => c.continent === continent);
}

export function countByContinent(): Record<string, number> {
  const out: Record<string, number> = {};
  for (const c of COUNTRIES) out[c.continent] = (out[c.continent] ?? 0) + 1;
  return out;
}

// The name shown to the player / used for letter hints (active locale).
export function displayName(c: GeoCountry, locale: Locale = currentLocale()): string {
  return locale === 'no' ? c.nameNo : c.nameEn;
}

// ---- Answer grading ---------------------------------------

// Lowercase, strip diacritics, drop punctuation, collapse whitespace.
export function normalize(s: string): string {
  return s
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9\s]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

// Every spelling we accept for a country: English + Norwegian + aliases.
export function acceptedNames(c: GeoCountry): string[] {
  const set = new Set<string>();
  for (const n of [c.nameEn, c.nameNo, ...c.aliases]) {
    const norm = normalize(n);
    if (norm) set.add(norm);
  }
  return [...set];
}

// Iterative Levenshtein distance.
export function levenshtein(a: string, b: string): number {
  if (a === b) return 0;
  if (!a.length) return b.length;
  if (!b.length) return a.length;
  let prev = Array.from({ length: b.length + 1 }, (_, i) => i);
  let curr = new Array<number>(b.length + 1);
  for (let i = 1; i <= a.length; i++) {
    curr[0] = i;
    for (let j = 1; j <= b.length; j++) {
      const cost = a[i - 1] === b[j - 1] ? 0 : 1;
      curr[j] = Math.min(prev[j] + 1, curr[j - 1] + 1, prev[j - 1] + cost);
    }
    [prev, curr] = [curr, prev];
  }
  return prev[b.length];
}

export interface GradeResult {
  correct: boolean;
  distance: number; // best (smallest) distance to an accepted spelling
}

// Correct if the input matches any accepted spelling within a tolerance that
// scales with that spelling's length (~20%, min 1) — forgiving of typos.
export function gradeAnswer(input: string, c: GeoCountry): GradeResult {
  const guess = normalize(input);
  if (!guess) return { correct: false, distance: Infinity };
  let best = Infinity;
  let correct = false;
  for (const name of acceptedNames(c)) {
    const d = levenshtein(guess, name);
    if (d < best) best = d;
    const tolerance = Math.max(1, Math.floor(name.length * 0.2));
    if (d <= tolerance) correct = true;
  }
  return { correct, distance: best };
}

// ---- Neighbours (for the 4-card hint) ---------------------

function haversine(a: GeoCountry, b: GeoCountry): number {
  const R = 6371;
  const dLat = ((b.lat - a.lat) * Math.PI) / 180;
  const dLng = ((b.lng - a.lng) * Math.PI) / 180;
  const la1 = (a.lat * Math.PI) / 180;
  const la2 = (b.lat * Math.PI) / 180;
  const h =
    Math.sin(dLat / 2) ** 2 + Math.cos(la1) * Math.cos(la2) * Math.sin(dLng / 2) ** 2;
  return 2 * R * Math.asin(Math.sqrt(h));
}

// The `n` nearest countries to `target` within the same continent.
export function nearestNeighbours(target: GeoCountry, n = 3): GeoCountry[] {
  return countriesIn(target.continent)
    .filter((c) => c.iso3 !== target.iso3)
    .sort((a, b) => haversine(target, a) - haversine(target, b))
    .slice(0, n);
}

// 4 shuffled options (the target + its 3 nearest neighbours) for the card hint.
export function cardOptions(target: GeoCountry): GeoCountry[] {
  return shuffle([target, ...nearestNeighbours(target, 3)]);
}

// ---- Hints + scoring --------------------------------------

// Reveal the first `count` letters of the answer (active locale), masking the
// rest. Spaces are always shown to hint word count.
export function letterHint(c: GeoCountry, count: number, locale: Locale = currentLocale()): string {
  const name = displayName(c, locale);
  let shown = 0;
  return [...name]
    .map((ch) => {
      if (ch === ' ') return ' ';
      shown += 1;
      return shown <= count ? ch : '_';
    })
    .join('');
}

// Points for a correct answer given hints consumed. No hints = full marks;
// each revealed letter costs 15, using the card hint caps the score.
export const MAX_SCORE = 100;
export function scoreFor(opts: { lettersRevealed: number; usedCards: boolean }): number {
  let score = MAX_SCORE - opts.lettersRevealed * 15;
  if (opts.usedCards) score = Math.min(score, 40);
  return Math.max(10, score);
}

// ---- utils -------------------------------------------------

export function shuffle<T>(arr: T[]): T[] {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}
